<a href="https://colab.research.google.com/github/MujahidMalik7/Portfolio-/blob/main/Oop_DSA_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
class Student:
  college_name = "PGC"
  def __init__ (self, fullname):
    self.fullname = fullname

s1 = Student("Mujahid")
print(s1.fullname)

print (s1.college_name)

Mujahid
PGC


In [ ]:
class Student:
  def __init__(self, name, marks):
    self.name = name
    self.marks = marks

  def get_avg(self):
    total_sum = 0
    for val in self.marks:
      total_sum = total_sum + val
    print("Student Name: ", self.name, "|| Average marks: ", total_sum/len(self.marks))

s1 = Student("Mujahid", [90,95,94])
print(s1.name)
s1.get_avg()

Mujahid
Student Name:  Mujahid || Average marks:  93.0


In [ ]:
## Static Methods
## they dont use the self parameters
## they are used when u dont need any objects , its a class level method

class Student:
    @staticmethod ##decortor is a function which takes function as parameter and gives output as function as well (changing behavior of a normal function).
    def college():
        print ("PGC College")

In [ ]:
# Abstraction
# hiding the implementation details of a class and
# only showing the essential features to the user

class Car:
  def __init__(self):
    self.acc = False
    self.brk = False
    self.clutch = False

  def start(self):
    self.acc = True
    self.clutch = True
    print ("Car Started")


car1 = Car()
car1.start()

Car Started


In [ ]:
class Account:
  def __init__(self, bal, acc):
    self.balance = bal
    self.account_number = acc

  def debit(self, amount):
    self.balance -= amount
    print ("Amount has been debited: ", amount)
    print ("Remaining Balance: ", self.balance)

  def deposit(self, amount):
    self.balance += amount
    print ("Amount has been deposited: ", amount)
    print ("Remaining Balance: ", self.balance)

acc1 = Account(1000, 123456789)
print(acc1.balance,acc1.account_number)
acc1.debit(200)
acc1.deposit(2000)


1000 123456789
Amount has been debited:  200
Remaining Balance:  800
Amount has been deposited:  2000
Remaining Balance:  2800


In [ ]:
## Super Class (jb child class s parent class k constructor method ko use kren)

class Car:
  def __init__(self, type):
    self.type = type

  @staticmethod
  def start():
    print ("Car Started")

  @staticmethod
  def stop():
    print ("Car Stopped")


class ToyotaCar(Car):
  def __init__(self, name, type):
    super().__init__(type)
    self.name = name


car1 = ToyotaCar("Prius", "Hybrid")
print(car1.name, car1.type)

Prius Hybrid


In [ ]:
## Class Method
# jsmn first parameter self ki bjaye obj hota hai

class Person:
  name = 'anonymous'

  def changeName (self, name):
    self.name = name    ##new name attribute add hoga
    Person.name = name  ## Class ka name attribute b change hogya
    self.__class__.name = name ## upr wla e kaam hoga idr b


p1 = Person()
p1.changeName("Mujahid")
print(p1.name)

print(Person.name)

Mujahid
Mujahid


In [ ]:
## Class Method
# jsmn first parameter self ki bjaye obj hota hai

class Person:
  name = 'anonymous'

  @classmethod
  def changeName (cls, name):
    cls.name = name   ## yh b class k attribute ko chng krega


p1 = Person()
p1.changeName("Mujahid")
print(p1.name)

print(Person.name)

Mujahid
Mujahid


In [ ]:
# Decorators
## getter setter
## staticmethod - jsmn koi arguments ni h ote koi attributes b ni hote new
## classmethod - self ki bjaye class k lye argument
## instancemethods - self

In [ ]:
#Property
# WE use @property decorator on any method in the class to use the method as a property.

class Student:
  def __init__(self, phy,chem,math):
    self.phy = phy
    self.chem = chem
    self.math = math

  # def calcPercentage(self):
  #   self.percentage = str((self.phy+self.chem+self.math) / 3) + "%"
  #rather than above code we can do the below one

  @property
  def calcPercentage(self):
    return str((self.phy+self.chem+self.math) / 3) + "%"

stu1 = Student(90,95,94)
print(stu1.calcPercentage)

stu1.phy = 69
print(stu1.calcPercentage)



93.0%
86.0%


In [ ]:
## Polymorphism
# Same operator is allowed to have different meaning according to the context.

print (1+3) #4 #addition
print (type(1+3)) #int
print ("Mujahid" + "Tufail") #concatenate
print (type("Mujahid" + "Tufail")) #str
print ([1,2,3] + [4,5]) #merge
print (type([1,2,3] + [4,5])) #list

# Har class k andar jo jo operators ka function kiya hua wh hora hai khud ba khud
# isi trh ham b apni class ka define kr skte |

4
<class 'int'>
MujahidTufail
<class 'str'>
[1, 2, 3, 4, 5]
<class 'list'>


In [ ]:
class Complex:
  def __init__(self, real, img):
    self.real = real
    self.img = img

  def showNumber(self):
    print(self.real, "i +", self.img, "j")

  ## Dunder Function
  def __add__(self, other):
    print ("------------")
    return Complex(self.real + other.real, self.img + other.img)

  def __sub__(self, other):
    print ("------------")
    return Complex(self.real - other.real, self.img - other.img)

num1 = Complex(2,3)
num1.showNumber()

num2 = Complex(3,4)
num2.showNumber()

num3 = num1 + num2
num3.showNumber()

print()
print()
print()

num1 = Complex(2,3)
num1.showNumber()

num2 = Complex(3,4)
num2.showNumber()

num4 = num1 - num2
num4.showNumber()


2 i + 3 j
3 i + 4 j
------------
5 i + 7 j



2 i + 3 j
3 i + 4 j
------------
-1 i + -1 j


In [ ]:
class Circle:
  def __init__(self, radius):
    self.radius = radius

  def area(self):
    return 3.14 * self.radius * self.radius

  def perimeter(self):
    return 2 * 3.14 * self.radius

c1 = Circle(5)
print ("Radius: ", c1.radius)
print("Area: " , c1.area())
print("Perimeter: ", c1.perimeter())


Radius:  5
Area:  78.5
Perimeter:  31.400000000000002


In [ ]:
class Employee:
  def __init__(self, role, dept, salary):
    self.role = role
    self.dept = dept
    self.salary = salary

  def showDetails(self):
    print("Role: ", self.role)
    print("Department: ", self.dept)
    print("Salary: ", self.salary)

class Engineer (Employee):
  def __init__(self, name, age):
    self.name = name
    self.age = age
    super().__init__("Engineer", "IT", "70000")


emp1 = Engineer("Mujahid", 22)
emp1.showDetails()

Role:  Engineer
Department:  IT
Salary:  70000


In [ ]:
class Order:
  def __init__(self, item, price):
    self.item = item
    self.price = price

  #true if self.price is greater than odr2.price else false
  def __gt__(self, odr2):
    return self.price > odr2.price


ord1 = Order("chips", 40)
ord2 = Order("burger", 35)

print(ord1 > ord2)

True


In [ ]:
import numpy as np

arr_1d = np.array([1,2,3,4])

print (arr_1d)
print()
arr_2d = np.array([[1,2,3], [4,5,6]])
print(arr_2d)
print()
element = arr_1d[2]
print ("Element: ", element)
print()
row = arr_2d[1]
print ("Row: ", row)
print()
specific_element = arr_2d[0,2]
print ("Specific Element: ", specific_element)
print()
subarray = arr_1d[1:4]
print ("Subarray: ", subarray)
print()
reshaped_arr = arr_1d.reshape(2,2)
print ("Reshaped Array: ", reshaped_arr)
print()
flattened_arr = arr_2d.flatten()
print ("Flattened Array: ", flattened_arr)
print()
concatenated_arr = np.concatenate([arr_1d, arr_1d])
print ("Concatenated Array: ", concatenated_arr)
print()
split_arr = np.split(arr_2d, 2, axis = 0)
print ("Split Array: ", split_arr)
print()
transposed_arr = arr_2d.T
print ("Transposed Array: ", transposed_arr)
print()
addition = arr_1d + 2
print ("Addition: ", addition)
print()
multiplication = arr_2d * 2
print ("Multiplication: ", multiplication)
print()
sorted_arr = np.sort(arr_1d)
print ("Sorted Array: ", sorted_arr)
print()
sorted_arr2 = np.sort(arr_2d, axis = 0)
print ("Sorted Array: ", sorted_arr2)
print()
mask  = arr_1d > 2
print ("Mask: ", mask)
print()
mask1 = arr_2d > 3
print ("Mask2: ", mask1)
print()

[1 2 3 4]

[[1 2 3]
 [4 5 6]]

Element:  3

Row:  [4 5 6]

Specific Element:  3

Subarray:  [2 3 4]

Reshaped Array:  [[1 2]
 [3 4]]

Flattened Array:  [1 2 3 4 5 6]

Concatenated Array:  [1 2 3 4 1 2 3 4]

Split Array:  [array([[1, 2, 3]]), array([[4, 5, 6]])]

Transposed Array:  [[1 4]
 [2 5]
 [3 6]]

Addition:  [3 4 5 6]

Multiplication:  [[ 2  4  6]
 [ 8 10 12]]

Sorted Array:  [1 2 3 4]

Sorted Array:  [[1 2 3]
 [4 5 6]]

Mask:  [False False  True  True]

Mask2:  [[False False False]
 [ True  True  True]]



In [ ]:
## Linked List

class Node:
  def __init__ (self, data):
    self.data = data
    self.next = None


class LinkedList:
  def __init__(self):
    self.head = None

  def append(self, data):
    new_node = Node(data)

    if self.head is None:
      self.head = new_node
      return

    current = self.head

    while current.next:
      current = current.next

    current.next = new_node

  def display (self):
    current = self.head

    while current:
      print(current.data, end = " -> ")
      current = current.next

    print("None")


l1 = LinkedList()
l1.append(1)
l1.append(2)
l1.append(3)
l1.display()

1 -> 2 -> 3 -> None


In [ ]:
class Node:
  def __init__(self, data):
    self.data = data
    self.next = None

class LinkedList:
  def __init__(self):
    self.head = None


  def append(self, data):
    new_node = Node(data)

    if self.head is None:
      self.head = new_node
      return

    current = self.head

    while current.next:
      current = current.next

    current.next = new_node

  def display(self):
    current = self.head

    while current:
      print(current.data , end = " -> ")
      current = current.next

    print ("None")


l1 = LinkedList()
l1.append(1)
l1.append(2)
l1.append(3)
l1.display()

1 -> 2 -> 3 -> None


In [ ]:
class Node:
  def __init__(self, data):
    self.data = data
    self.next = None


class LinkedList:
  def __init__(self):
    self.head = None

  def append(self, data):
    new_node = Node(data)

    if self.head is None:
      self.head = new_node
      return

    current = self.head

    while current.next:
      current = current.next

    current.next = new_node

  def display(self):
    current = self.head

    while current:
      print(current.data, end = " -> ")
      current = current.next

    print ("None")

l1 = LinkedList()
l1.append(1)
l1.append(2)
l1.append(3)
l1.display()


1 -> 2 -> 3 -> None


In [ ]:
class Node:
  def __init__(self, data):
    self.data = data
    self.next = None


class LinkedList:
  def __init__(self):
    self.head = None

  def append(self,data):
    new_node = Node(data)

    if self.head is None:
      self.head = new_node
      return

    current = self.head

    while current.next:
      current = current.next

    current.next = new_node

  def display(self):
    current = self.head

    while current:
      print(current.data , end = " -> ")
      current = current.next

    print ("None")

l1 = LinkedList()
l1.append(10)
l1.append(20)
l1.append(30)
l1.display()

10 -> 20 -> 30 -> None


In [ ]:
class Node:
  def __init__(self, data):
    self.data = data
    self.next = None

class LinkedList:
  def __init__(self):
    self.head = None

  def append(self,data):
    new_node = Node(data)

    if self.head is None:
      self.head = new_node
      return

    current = self.head

    while current.next:
      current = current.next

    current.next = new_node

  def display(self):
    current = self.head

    while current:
      print(current.data, end = " -> ")
      current = current.next

    print("None")

l1 = LinkedList()
l1.append(10)
l1.append(20)
l1.append(30)
l1.display()

10 -> 20 -> 30 -> None


In [ ]:
## reverse Array

def reverseArr(arr):
  n = len(arr)

  for i in range(n//2):
    arr[i], arr[n-i-1] = arr[n-i-1], arr[i]
  return arr


arr = [1,2,3,4,5,6,7,8,9,10]
print ("Array: ", arr)
print("Reverse Array: ", reverseArr(arr))

Array:  [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
Reverse Array:  [10, 9, 8, 7, 6, 5, 4, 3, 2, 1]


In [ ]:
def find_min_max(arr):
    n = len(arr)

    if n % 2 == 0:
        # even number of elements
        if arr[0] < arr[1]:
            minimum = arr[0]
            maximum = arr[1]
        else:
            minimum = arr[1]
            maximum = arr[0]
        start = 2
    else:
        # odd number of elements
        minimum = maximum = arr[0]
        start = 1

    for i in range(start, n, 2):
        if i+1 >= n:
            # if odd element at the end
            if arr[i] < minimum:
                minimum = arr[i]
            if arr[i] > maximum:
                maximum = arr[i]
            break

        # Compare in pairs first
        if arr[i] < arr[i+1]:
            local_min = arr[i]
            local_max = arr[i+1]
        else:
            local_min = arr[i+1]
            local_max = arr[i]

        # Compare with current min and max
        if local_min < minimum:
            minimum = local_min
        if local_max > maximum:
            maximum = local_max

    return minimum, maximum

# Example
arr = [3, 1, 4, 2, 5, 0]
mn, mx = find_min_max(arr)
print("Min:", mn, "Max:", mx)


Min: 0 Max: 5


In [ ]:
def merge_sorted_arrays(arr1, arr2):
    i = j = 0
    merged = []

    # Merge elements from both arrays
    while i < len(arr1) and j < len(arr2):
        if arr1[i] <= arr2[j]:
            merged.append(arr1[i])
            i += 1
        else:
            merged.append(arr2[j])
            j += 1

    # Add remaining elements from arr1
    while i < len(arr1):
        merged.append(arr1[i])
        i += 1

    # Add remaining elements from arr2
    while j < len(arr2):
        merged.append(arr2[j])
        j += 1

    return merged

# Example
arr1 = [1, 3, 5]
arr2 = [2, 4, 6]
result = merge_sorted_arrays(arr1, arr2)
print(result)  # Output: [1, 2, 3, 4, 5, 6]


[1, 2, 3, 4, 5, 6]


In [ ]:
def merge_sort_arr(arr1, arr2):
  i = j = 0
  merged = []

  while i<len(arr1) and j<len(arr2):
    if arr1[i] <= arr2[j]:
      merged.append(arr1[i])
      i+=1
    else:
      merged.append(arr2[j])
      j+=1

  while i<len(arr1):
    merged.append(arr1[i])
    i+=1

  while j<len(arr2):
    merged.append(arr2[j])
    j+=1

  return mergedx


def insertionSort(arr):
  for i in range(1, len(arr)):
    key = arr[i]
    j = i-1

    while j>=0 and arr[j] > key:
      arr[j+1] = arr[j]
      j-=1
    arr[j+1] = key
  return arr

# i = 1 , key = arr[1] = 5, j = 0 ,,, 1 < 5,,, arr[1] = 5
# 1,5,2,4,8,3,8
# i = 2, key = arr[2] = 2, j = 1  ,,, j1 and 5>2 ,,, [2]=[1], 2,5 j=0 ,,, arr[0] > 2,,,


arr1 = [1,5,2,4,8,3,8]

arr2 = [2,4,3,10,5,7,6,9]
print(insertionSort(arr1))
print(insertionSort(arr2))

print (merge_sort_arr(arr1,arr2))

print (set(merge_sort_arr(arr1,arr2)))


[1, 2, 3, 4, 5, 8, 8]
[2, 3, 4, 5, 6, 7, 9, 10]
[1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 7, 8, 8, 9, 10]
{1, 2, 3, 4, 5, 6, 7, 8, 9, 10}


In [ ]:
def searchArr(arr1,arr2):
  for x in arr2:
    if x not in arr1:
      return False
  return True

arr1 = [4,3,2,1,6,4,5,7,8,4,]
arr2 = [4,1,6,5]

searchArr(arr1,arr2)

True

In [ ]:
## Linkedlist k center wala number

class Node:
  def __init__(self,data):
    self.data = data
    self.next = None


class LinkedList:

  def __init__(self):
    self.head = None

  def append(self, data):
    new_node = Node(data)

    if (self.head is None):
      self.head = new_node
      return

    current = self.head
    while current.next:
      current = current.next

    current.next = new_node


  def display(self):
    current = self.head
    while current:
      print (current.data, end=" -> ")
      current = current.next

    print ("None")

  def findMiddle(self):
    slow = self.head
    fast = self.head

    while (fast and fast.next):
      fast = fast.next.next
      slow = slow.next
    print ("Middle Node: " , slow.data)

l1 = LinkedList()
l1.append(1)
l1.append(2)
l1.append(3)
l1.append(4)
l1.append(5)
l1.append(6)
l1.append(7)
l1.display()
l1.findMiddle()

1 -> 2 -> 3 -> 4 -> 5 -> 6 -> 7 -> None
Middle Node:  4


In [ ]:
def counter(arr, number):
  count = 0
  for i in range (0,len(arr),1):
   if arr[i] == number:
    count +=1
  return count

arr1 = [4,4,6,7,6,8,5,3,4]
num = int(input("Enter number you want to find count of: "))
counter(arr1,num)


Enter number you want to find count of: 4


3

In [ ]:
class Student:
  def __init__ (self, name, marks):
    self.name = name
    self.marks = marks

  def display(self):
    print ("Name: ", self.name)
    print ("Marks: ", self.marks)

  def grade(self):
    if self.marks >= 90:
      print ("Grade: A")
    elif self.marks >= 80:
      print ("Grade: B")
    elif self.marks >= 70:
      print ("Grade: C")
    elif self.marks >= 60:
      print ("Grade: D")
    else:
      print ("Fail")

    def display(self):
        print("Name:", self.name)
        print("Marks:", self.marks)
        print("Grade:", self.grade())
        print()

students = [
    Student("Mujahid", 85),
    Student("Ali",90),
    Student("Shayan", 45),
    Student("Malaika", 56),
    Student("Mars", 69)
]

topper = students[0]

print ("-----------------------")
print ("Passed Students ")
print()

for student in students:
  if (student.marks > 60):
    student.display()
    print()

print ("-----------------------")
print ("Failed Students")
print()

for student in students:
  if (student.marks < 60):
    student.display()
    print()

  if (student.marks > topper.marks):
    topper = student
print ("-----------------------")
print()
print ("Topper: ", topper.name)


-----------------------
Passed Students 

Name:  Mujahid
Marks:  85

Name:  Ali
Marks:  90

Name:  Mars
Marks:  69

-----------------------
Failed Students

Name:  Shayan
Marks:  45

Name:  Malaika
Marks:  56

-----------------------

Topper:  Ali


In [4]:
def isPrime(num):
  if num < 2:
    return False
  for i in range (2, int(num**0.5) + 1):
    if (num % i == 0):
      return False
  return True

count = 0
numbertoCheck = 2
prime = []
num= int(input("Enter total numbers:  "))

while count < num:
  if (isPrime(numbertoCheck)):
    print (numbertoCheck)
    prime.append(numbertoCheck)
    count +=1
  numbertoCheck +=1

Enter total numbers:  10
2
3
5
7
11
13
17
19
23
29


In [12]:
def fibboseries (n):
  if n <= 0:
    return
  a,b = 0,1
  count = 0
  while count  < n:
    if count == 0:
      print (a)
      count +=1
    if count == 1:
      print (b)
      count +=1
    else:
      next = a + b
      a = b
      b = next
      print (next)
      count += 1

num = int ( input ("Enter Numbers: "))

fibboseries(num)

Enter Numbers: 10
0
1
1
2
3
5
8
13
21
34
